spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demoWithTests
    schema: public
    username: postgres
    password: password

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: validate # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #open-in-view: false
    #generate-ddl: true

  #Flyway
  flyway:
    driverClassName: org.postgresql.Driver
    user: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/demoWithTests
    schemas: public
    enabled: true
    baseline-on-migrate: true

    #security
    security:
      user:
        name: admin
        password: admin

  #MultipartSize
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: debug
    org.hibernate: debug

# Server configuration
server:
  port: 8087

# Swagger configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html # swagger-ui custom path
  api-docs:
    path: /v3/api-docs.yaml




