# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demoWithTests
    username: postgres
    password: password
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #open-in-view: false
    #generate-ddl: true
  flyway:
    #    locations: filesystem:.\src\main\resources\db\migration
    enabled: false
    #    clean-disabled: true
    baseline-on-migrate: true
#  security:
#    user:
#      name: admin
#      password: admin
#MultipartSize
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: debug
    org.hibernate: debug
# Server configuration
server:
  port: 8087 #set your port
# Swagger configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html # swagger-ui custom path
  api-docs:
    path: /v3/api-docs.yaml




